<?php
/**
 * ACF Config (Free Version)
 * Los campos se configuran visualmente o mediante importación JSON (acf-export-gratis.json).
 * Al ser la versión gratuita, no usamos acf_add_options_page() aquí.
 */

// Si necesitas registrar campos locales vía PHP en el futuro, puedes hacerlo aquí.
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_home_portfolio',
	'title' => 'Contenido Destacado de la Portada',
	'fields' => array(
		array(
			'key' => 'field_home_featured_projects',
			'label' => 'Proyectos Destacados',
			'name' => 'home_featured_projects',
			'type' => 'relationship',
			'instructions' => 'Selecciona y ordena los proyectos que deseas mostrar en la portada. Si lo dejas vacío, se mostrarán los últimos.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'proyecto',
			),
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'taxonomy',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
		array(
			'key' => 'field_home_featured_testimonials',
			'label' => 'Opiniones Destacadas',
			'name' => 'home_featured_testimonials',
			'type' => 'relationship',
			'instructions' => 'Selecciona y ordena las opiniones (testimonios) a mostrar (Máximo 6). Si lo dejas vacío, se mostrarán los últimos.',
			'required' => 0,
			'conditional_logic' => 0,
			'post_type' => array(
				0 => 'testimonio',
			),
			'filters' => array(
				0 => 'search',
			),
			'max' => 6,
			'return_format' => 'object',
		),
		array(
			'key' => 'field_home_featured_services',
			'label' => 'Servicios Destacados',
			'name' => 'home_featured_services',
			'type' => 'relationship',
			'instructions' => 'Selecciona y ordena los servicios a mostrar. Si lo dejas vacío, se mostrarán todos.',
			'required' => 0,
			'conditional_logic' => 0,
			'post_type' => array(
				0 => 'servicio',
			),
			'filters' => array(
				0 => 'search',
			),
			'return_format' => 'object',
		),
		array(
			'key' => 'field_home_featured_faq',
			'label' => 'Preguntas Frecuentes (FAQ) Destacadas',
			'name' => 'home_featured_faq',
			'type' => 'relationship',
			'instructions' => 'Selecciona y ordena las FAQs a mostrar. Si lo dejas vacío, se mostrarán todas.',
			'required' => 0,
			'conditional_logic' => 0,
			'post_type' => array(
				0 => 'faq',
			),
			'filters' => array(
				0 => 'search',
			),
			'return_format' => 'object',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_proyecto_testimonio',
	'title' => 'Testimonio Asociado',
	'fields' => array(
		array(
			'key' => 'field_testimonio_asociado',
			'label' => 'Testimonio del Cliente',
			'name' => 'testimonio_asociado',
			'type' => 'post_object',
			'instructions' => 'Selecciona un testimonio para mostrar en la página individual de este proyecto.',
			'required' => 0,
			'post_type' => array(
				0 => 'testimonio',
			),
			'return_format' => 'object',
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'proyecto',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
));

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_testimonio_meta',
	'title' => 'Datos del Testimonio',
	'fields' => array(
		array(
			'key' => 'field_testimonial_content',
			'label' => 'Reseña',
			'name' => 'testimonial_content',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_testimonial_country',
			'label' => 'País',
			'name' => 'testimonial_country',
			'type' => 'text',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'testimonio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
));

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_sobre_mi_page',
	'title' => 'Ajustes de Sobre Mí',
	'fields' => array(
		array(
			'key' => 'tab_sobre_mi_hero',
			'label' => 'Hero',
			'type' => 'tab',
		),
		array(
			'key' => 'field_sobre_mi_hero_kicker',
			'label' => 'Kicker',
			'name' => 'sobre_mi_hero_kicker',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_hero_headline_prefix',
			'label' => 'Titular (Prefijo)',
			'name' => 'sobre_mi_hero_headline_prefix',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_hero_headline_highlight',
			'label' => 'Titular (Destacado)',
			'name' => 'sobre_mi_hero_headline_highlight',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_hero_description',
			'label' => 'Descripción',
			'name' => 'sobre_mi_hero_description',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_sobre_mi_metric_1_number',
			'label' => 'Métrica 1 (Número)',
			'name' => 'sobre_mi_metric_1_number',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_metric_1_label',
			'label' => 'Métrica 1 (Etiqueta)',
			'name' => 'sobre_mi_metric_1_label',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_metric_2_number',
			'label' => 'Métrica 2 (Número)',
			'name' => 'sobre_mi_metric_2_number',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_metric_2_label',
			'label' => 'Métrica 2 (Etiqueta)',
			'name' => 'sobre_mi_metric_2_label',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_metric_3_number',
			'label' => 'Métrica 3 (Número)',
			'name' => 'sobre_mi_metric_3_number',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_metric_3_label',
			'label' => 'Métrica 3 (Etiqueta)',
			'name' => 'sobre_mi_metric_3_label',
			'type' => 'text',
		),
		array(
			'key' => 'tab_sobre_mi_bio',
			'label' => 'Biografía',
			'type' => 'tab',
		),
		array(
			'key' => 'field_sobre_mi_bio_headline_prefix',
			'label' => 'Titular (Prefijo)',
			'name' => 'sobre_mi_bio_headline_prefix',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_bio_headline_highlight',
			'label' => 'Titular (Destacado)',
			'name' => 'sobre_mi_bio_headline_highlight',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_bio_text_1',
			'label' => 'Texto Principal',
			'name' => 'sobre_mi_bio_text_1',
			'type' => 'wysiwyg',
			'media_upload' => 0,
		),
		array(
			'key' => 'field_sobre_mi_bio_quote',
			'label' => 'Frase Destacada (Quote)',
			'name' => 'sobre_mi_bio_quote',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_sobre_mi_bio_text_2',
			'label' => 'Texto Secundario',
			'name' => 'sobre_mi_bio_text_2',
			'type' => 'wysiwyg',
			'media_upload' => 0,
		),
		array(
			'key' => 'tab_sobre_mi_trayectoria',
			'label' => 'Trayectoria',
			'type' => 'tab',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_headline',
			'label' => 'Titular',
			'name' => 'sobre_mi_trayectoria_headline',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_1_period',
			'label' => 'Trayectoria 1 (Período)',
			'name' => 'sobre_mi_trayectoria_1_period',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_1_role',
			'label' => 'Trayectoria 1 (Rol)',
			'name' => 'sobre_mi_trayectoria_1_role',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_1_description',
			'label' => 'Trayectoria 1 (Descripción)',
			'name' => 'sobre_mi_trayectoria_1_description',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_2_period',
			'label' => 'Trayectoria 2 (Período)',
			'name' => 'sobre_mi_trayectoria_2_period',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_2_role',
			'label' => 'Trayectoria 2 (Rol)',
			'name' => 'sobre_mi_trayectoria_2_role',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_2_description',
			'label' => 'Trayectoria 2 (Descripción)',
			'name' => 'sobre_mi_trayectoria_2_description',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_3_period',
			'label' => 'Trayectoria 3 (Período)',
			'name' => 'sobre_mi_trayectoria_3_period',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_3_role',
			'label' => 'Trayectoria 3 (Rol)',
			'name' => 'sobre_mi_trayectoria_3_role',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_3_description',
			'label' => 'Trayectoria 3 (Descripción)',
			'name' => 'sobre_mi_trayectoria_3_description',
			'type' => 'textarea',
		),
		array(
			'key' => 'tab_sobre_mi_valores',
			'label' => 'Valores',
			'type' => 'tab',
		),
		array(
			'key' => 'field_sobre_mi_valores_headline',
			'label' => 'Titular',
			'name' => 'sobre_mi_valores_headline',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_valores_text',
			'label' => 'Texto de Valores',
			'name' => 'sobre_mi_valores_text',
			'type' => 'wysiwyg',
			'media_upload' => 0,
		),
		array(
			'key' => 'tab_sobre_mi_cta',
			'label' => 'Llamado a la Acción (CTA)',
			'type' => 'tab',
		),
		array(
			'key' => 'field_sobre_mi_cta_headline',
			'label' => 'Titular',
			'name' => 'sobre_mi_cta_headline',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_cta_subheadline',
			'label' => 'Subtítulo',
			'name' => 'sobre_mi_cta_subheadline',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_sobre_mi_cta_btn_label',
			'label' => 'Etiqueta del Botón',
			'name' => 'sobre_mi_cta_btn_label',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_cta_btn_url',
			'label' => 'URL del Botón',
			'name' => 'sobre_mi_cta_btn_url',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_cta_guarantee',
			'label' => 'Garantía / Nota bajo el botón',
			'name' => 'sobre_mi_cta_guarantee',
			'type' => 'text',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-sobre-mi.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
));

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_global_hero_cta',
	'title' => 'Configuración de Página (Héroe y CTA)',
	'fields' => array(
		array('key' => 'field_hero_kicker', 'label' => 'Kicker (Subtítulo superior)', 'name' => 'hero_kicker', 'type' => 'text'),
		array('key' => 'field_hero_h1_normal', 'label' => 'H1 Texto Normal', 'name' => 'hero_h1_normal', 'type' => 'text'),
		array('key' => 'field_hero_h1_highlight', 'label' => 'H1 Texto Resaltado', 'name' => 'hero_h1_highlight', 'type' => 'text'),
		array('key' => 'field_hero_description', 'label' => 'Descripción del Héroe', 'name' => 'hero_description', 'type' => 'textarea', 'rows' => 3),
		array('key' => 'field_cta_kicker', 'label' => 'CTA Kicker', 'name' => 'cta_kicker', 'type' => 'text'),
		array('key' => 'field_cta_h2', 'label' => 'CTA Título', 'name' => 'cta_h2', 'type' => 'text'),
		array('key' => 'field_cta_description', 'label' => 'CTA Descripción', 'name' => 'cta_description', 'type' => 'textarea', 'rows' => 3),
		array('key' => 'field_cta_button_text', 'label' => 'CTA Botón Texto', 'name' => 'cta_button_text', 'type' => 'text'),
		array('key' => 'field_cta_button_url', 'label' => 'CTA Botón URL', 'name' => 'cta_button_url', 'type' => 'text'),
	),
	'location' => array(
		array(array('param' => 'page_template', 'operator' => '==', 'value' => 'page-servicios.php')),
		array(array('param' => 'page_template', 'operator' => '==', 'value' => 'page-portafolio.php')),
		array(array('param' => 'page_template', 'operator' => '==', 'value' => 'page-blog.php')),
		array(array('param' => 'page_template', 'operator' => '==', 'value' => 'page-contacto.php')),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
));

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_servicios_contenido',
	'title' => 'Contenido Servicios',
	'fields' => array(
		array('key' => 'field_servicios_para_ti', 'label' => 'Esto es para ti (Una por línea)', 'name' => 'servicios_para_ti', 'type' => 'textarea', 'rows' => 5),
		array('key' => 'field_servicios_no_para_ti', 'label' => 'Esto NO es para ti (Una por línea)', 'name' => 'servicios_no_para_ti', 'type' => 'textarea', 'rows' => 5),
		array('key' => 'field_servicios_proceso_1_titulo', 'label' => 'Proceso Paso 1 Título', 'name' => 'servicios_proceso_1_titulo', 'type' => 'text'),
		array('key' => 'field_servicios_proceso_1_desc', 'label' => 'Proceso Paso 1 Descripción', 'name' => 'servicios_proceso_1_desc', 'type' => 'textarea', 'rows' => 2),
		array('key' => 'field_servicios_proceso_2_titulo', 'label' => 'Proceso Paso 2 Título', 'name' => 'servicios_proceso_2_titulo', 'type' => 'text'),
		array('key' => 'field_servicios_proceso_2_desc', 'label' => 'Proceso Paso 2 Descripción', 'name' => 'servicios_proceso_2_desc', 'type' => 'textarea', 'rows' => 2),
		array('key' => 'field_servicios_proceso_3_titulo', 'label' => 'Proceso Paso 3 Título', 'name' => 'servicios_proceso_3_titulo', 'type' => 'text'),
		array('key' => 'field_servicios_proceso_3_desc', 'label' => 'Proceso Paso 3 Descripción', 'name' => 'servicios_proceso_3_desc', 'type' => 'textarea', 'rows' => 2),
	),
	'location' => array(
		array(array('param' => 'page_template', 'operator' => '==', 'value' => 'page-servicios.php')),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
));

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_contacto_faq',
	'title' => 'Configuración Contacto',
	'fields' => array(
		array('key' => 'field_contacto_faq_titulo', 'label' => 'FAQ Título', 'name' => 'contacto_faq_titulo', 'type' => 'text'),
		array('key' => 'field_contacto_faq_desc', 'label' => 'FAQ Descripción', 'name' => 'contacto_faq_desc', 'type' => 'textarea', 'rows' => 2),
	),
	'location' => array(
		array(array('param' => 'page_template', 'operator' => '==', 'value' => 'page-contacto.php')),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
));

acf_add_local_field_group(array (
  'ID' => '',
  'ID' => '',
  'key' => 'group_home_page',
  'title' => 'Ajustes de Inicio (Home)',
  'fields' => 
  array (
    0 => 
    array (
      'key' => 'field_tab_hero',
      'label' => 'Hero',
      'name' => '',
      'aria-label' => '',
      'type' => 'tab',
      'value' => false,
      'menu_order' => 0,
      'instructions' => '',
      'required' => 0,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
      'selected' => 0,
    ),
    1 => 
    array (
      'key' => 'field_hero_headline',
      'label' => 'Titular (Headline)',
      'name' => 'hero_headline',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 1,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    2 => 
    array (
      'key' => 'field_hero_subheadline',
      'label' => 'Subtítulo (Subheadline)',
      'name' => 'hero_subheadline',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 2,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    3 => 
    array (
      'key' => 'field_hero_cta_label',
      'label' => 'Texto del Botón',
      'name' => 'hero_cta_label',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 3,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    4 => 
    array (
      'key' => 'field_hero_cta_url',
      'label' => 'URL del Botón',
      'name' => 'hero_cta_url',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 4,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    5 => 
    array (
      'key' => 'field_home_hero_kicker',
      'label' => 'Kicker (Texto sobre el título)',
      'name' => 'hero_kicker',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 5,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    6 => 
    array (
      'key' => 'field_home_hero_image',
      'label' => 'Imagen del Hero',
      'name' => 'hero_image',
      'aria-label' => '',
      'type' => 'image',
      'value' => NULL,
      'menu_order' => 6,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'medium',
      'library' => 'all',
      'min_width' => 0,
      'min_height' => 0,
      'min_size' => 0,
      'max_width' => 0,
      'max_height' => 0,
      'max_size' => 0,
      'mime_types' => '',
    ),
    7 => 
    array (
      'key' => 'field_tab_metrics',
      'label' => 'Métricas',
      'name' => '',
      'aria-label' => '',
      'type' => 'tab',
      'value' => false,
      'menu_order' => 7,
      'instructions' => '',
      'required' => 0,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
      'selected' => 0,
    ),
    8 => 
    array (
      'key' => 'field_metric_1_val',
      'label' => 'Métrica 1 - Valor',
      'name' => 'metric_1_val',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 8,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    9 => 
    array (
      'key' => 'field_metric_1_lab',
      'label' => 'Métrica 1 - Etiqueta',
      'name' => 'metric_1_lab',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 9,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    10 => 
    array (
      'key' => 'field_metric_2_val',
      'label' => 'Métrica 2 - Valor',
      'name' => 'metric_2_val',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 10,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    11 => 
    array (
      'key' => 'field_metric_2_lab',
      'label' => 'Métrica 2 - Etiqueta',
      'name' => 'metric_2_lab',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 11,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    12 => 
    array (
      'key' => 'field_metric_3_val',
      'label' => 'Métrica 3 - Valor',
      'name' => 'metric_3_val',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 12,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    13 => 
    array (
      'key' => 'field_metric_3_lab',
      'label' => 'Métrica 3 - Etiqueta',
      'name' => 'metric_3_lab',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 13,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    14 => 
    array (
      'key' => 'field_tab_about',
      'label' => 'Sobre Mí',
      'name' => '',
      'aria-label' => '',
      'type' => 'tab',
      'value' => false,
      'menu_order' => 14,
      'instructions' => '',
      'required' => 0,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
      'selected' => 0,
    ),
    15 => 
    array (
      'key' => 'field_about_headline',
      'label' => 'Titular',
      'name' => 'about_headline',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 15,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    16 => 
    array (
      'key' => 'field_about_bio',
      'label' => 'Biografía',
      'name' => 'about_bio',
      'aria-label' => '',
      'type' => 'wysiwyg',
      'value' => NULL,
      'menu_order' => 16,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
      'default_value' => '',
      'delay' => 0,
    ),
    17 => 
    array (
      'key' => 'field_tab_methodology',
      'label' => 'Metodología',
      'name' => '',
      'aria-label' => '',
      'type' => 'tab',
      'value' => false,
      'menu_order' => 17,
      'instructions' => '',
      'required' => 0,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
      'selected' => 0,
    ),
    18 => 
    array (
      'key' => 'field_method_kicker',
      'label' => 'Kicker (Ej: Metodología)',
      'name' => 'method_kicker',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 18,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    19 => 
    array (
      'key' => 'field_method_title',
      'label' => 'Título Principal',
      'name' => 'method_title',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 19,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    20 => 
    array (
      'key' => 'field_method_desc',
      'label' => 'Descripción General',
      'name' => 'method_desc',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 20,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    21 => 
    array (
      'key' => 'field_step_1_letter',
      'label' => 'Paso 1 - Letra',
      'name' => 'step_1_letter',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 21,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    22 => 
    array (
      'key' => 'field_step_1_title',
      'label' => 'Paso 1 - Título',
      'name' => 'step_1_title',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 22,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    23 => 
    array (
      'key' => 'field_step_1_desc',
      'label' => 'Paso 1 - Descripción',
      'name' => 'step_1_desc',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 23,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    24 => 
    array (
      'key' => 'field_step_2_letter',
      'label' => 'Paso 2 - Letra',
      'name' => 'step_2_letter',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 24,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    25 => 
    array (
      'key' => 'field_step_2_title',
      'label' => 'Paso 2 - Título',
      'name' => 'step_2_title',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 25,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    26 => 
    array (
      'key' => 'field_step_2_desc',
      'label' => 'Paso 2 - Descripción',
      'name' => 'step_2_desc',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 26,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    27 => 
    array (
      'key' => 'field_step_3_letter',
      'label' => 'Paso 3 - Letra',
      'name' => 'step_3_letter',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 27,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    28 => 
    array (
      'key' => 'field_step_3_title',
      'label' => 'Paso 3 - Título',
      'name' => 'step_3_title',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 28,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    29 => 
    array (
      'key' => 'field_step_3_desc',
      'label' => 'Paso 3 - Descripción',
      'name' => 'step_3_desc',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 29,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    30 => 
    array (
      'key' => 'field_step_4_letter',
      'label' => 'Paso 4 - Letra',
      'name' => 'step_4_letter',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 30,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    31 => 
    array (
      'key' => 'field_step_4_title',
      'label' => 'Paso 4 - Título',
      'name' => 'step_4_title',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 31,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    32 => 
    array (
      'key' => 'field_step_4_desc',
      'label' => 'Paso 4 - Descripción',
      'name' => 'step_4_desc',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 32,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    33 => 
    array (
      'key' => 'field_step_5_letter',
      'label' => 'Paso 5 - Letra',
      'name' => 'step_5_letter',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 33,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    34 => 
    array (
      'key' => 'field_step_5_title',
      'label' => 'Paso 5 - Título',
      'name' => 'step_5_title',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 34,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    35 => 
    array (
      'key' => 'field_step_5_desc',
      'label' => 'Paso 5 - Descripción',
      'name' => 'step_5_desc',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 35,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    36 => 
    array (
      'key' => 'field_tab_footer',
      'label' => 'Global / Footer',
      'name' => '',
      'aria-label' => '',
      'type' => 'tab',
      'value' => false,
      'menu_order' => 36,
      'instructions' => '',
      'required' => 0,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
      'selected' => 0,
    ),
    37 => 
    array (
      'key' => 'field_footer_email',
      'label' => 'Email de Contacto',
      'name' => 'footer_email',
      'aria-label' => '',
      'type' => 'email',
      'value' => NULL,
      'menu_order' => 37,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    38 => 
    array (
      'key' => 'field_footer_copy',
      'label' => 'Texto Copyright',
      'name' => 'footer_copy',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 38,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    39 => 
    array (
      'key' => 'field_home_cta_tab',
      'label' => 'Llamado a la Acción (CTA)',
      'name' => '',
      'aria-label' => '',
      'type' => 'tab',
      'value' => false,
      'menu_order' => 39,
      'instructions' => '',
      'required' => 0,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
      'selected' => 0,
    ),
    40 => 
    array (
      'key' => 'field_home_cta_headline',
      'label' => 'Título del CTA',
      'name' => 'cta_headline',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 40,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    41 => 
    array (
      'key' => 'field_home_cta_subheadline',
      'label' => 'Subtítulo del CTA',
      'name' => 'cta_subheadline',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 41,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'rows' => 3,
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
    ),
    42 => 
    array (
      'key' => 'field_home_cta_btn_label',
      'label' => 'Texto del Botón CTA',
      'name' => 'cta_btn_label',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 42,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    43 => 
    array (
      'key' => 'field_home_cta_btn_url',
      'label' => 'URL del Botón CTA',
      'name' => 'cta_btn_url',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 43,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
  ),
  'location' => 
  array (
    0 => 
    array (
      0 => 
      array (
        'param' => 'page_type',
        'operator' => '==',
        'value' => 'front_page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => 
  array (
    0 => 'the_content',
  ),
  'active' => true,
  'description' => '',
  'show_in_rest' => false,
  'display_title' => '',
  'allow_ai_access' => false,
  'ai_description' => '',
  '_valid' => true,
));

acf_add_local_field_group(array (
  'ID' => '',
  'ID' => '',
  'key' => 'group_service_details',
  'title' => 'Detalles del Servicio',
  'fields' => 
  array (
    0 => 
    array (
      'key' => 'field_service_icon',
      'label' => 'Nombre del Icono (Ej: code)',
      'name' => 'icon',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 0,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    1 => 
    array (
      'key' => 'field_service_desc',
      'label' => 'Descripción Corta',
      'name' => 'desc',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 1,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    2 => 
    array (
      'key' => 'field_service_features',
      'label' => 'Características (Una por línea)',
      'name' => 'features',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 2,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
  ),
  'location' => 
  array (
    0 => 
    array (
      0 => 
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'servicio',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => 
  array (
  ),
  'active' => true,
  'description' => '',
  'show_in_rest' => false,
  'display_title' => '',
  'allow_ai_access' => false,
  'ai_description' => '',
  '_valid' => true,
));

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_portfolio_settings',
	'title' => 'Ajustes de Portafolio',
	'fields' => array(
		array(
			'key' => 'field_portfolio_sort_order',
			'label' => 'Orden de los Proyectos',
			'name' => 'portfolio_sort_order',
			'type' => 'select',
			'instructions' => 'Selecciona cómo quieres que se ordenen los proyectos en esta página.',
			'choices' => array(
				'date_asc' => 'Más antiguos primero (Fecha de Creación)',
				'date_desc' => 'Más recientes primero (Fecha de Creación)',
				'modified_asc' => 'Más antiguos primero (Fecha de Modificación)',
				'modified_desc' => 'Más recientes primero (Fecha de Modificación)',
				'title_asc' => 'Alfabético (A-Z)',
			),
			'default_value' => 'date_asc',
			'return_format' => 'value',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-portafolio.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
));

endif;
