<?php
/**
 * ACF Config (Free Version)
 * Los campos se configuran visualmente o mediante importación JSON (acf-export-gratis.json).
 * Al ser la versión gratuita, no usamos acf_add_options_page() aquí.
 */

// Si necesitas registrar campos locales vía PHP en el futuro, puedes hacerlo aquí.
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_home_portfolio',
	'title' => 'Contenido Destacado de la Portada',
	'fields' => array(
		array(
			'key' => 'field_home_featured_projects',
			'label' => 'Proyectos Destacados',
			'name' => 'home_featured_projects',
			'type' => 'relationship',
			'instructions' => 'Selecciona y ordena los proyectos que deseas mostrar en la portada. Si lo dejas vacío, se mostrarán los últimos.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'proyecto',
			),
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'taxonomy',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
		array(
			'key' => 'field_home_featured_testimonials',
			'label' => 'Opiniones Destacadas',
			'name' => 'home_featured_testimonials',
			'type' => 'relationship',
			'instructions' => 'Selecciona y ordena las opiniones (testimonios) a mostrar (Máximo 6). Si lo dejas vacío, se mostrarán los últimos.',
			'required' => 0,
			'conditional_logic' => 0,
			'post_type' => array(
				0 => 'testimonio',
			),
			'filters' => array(
				0 => 'search',
			),
			'max' => 6,
			'return_format' => 'object',
		),
		array(
			'key' => 'field_home_featured_services',
			'label' => 'Servicios Destacados',
			'name' => 'home_featured_services',
			'type' => 'relationship',
			'instructions' => 'Selecciona y ordena los servicios a mostrar. Si lo dejas vacío, se mostrarán todos.',
			'required' => 0,
			'conditional_logic' => 0,
			'post_type' => array(
				0 => 'servicio',
			),
			'filters' => array(
				0 => 'search',
			),
			'return_format' => 'object',
		),
		array(
			'key' => 'field_home_featured_faq',
			'label' => 'Preguntas Frecuentes (FAQ) Destacadas',
			'name' => 'home_featured_faq',
			'type' => 'relationship',
			'instructions' => 'Selecciona y ordena las FAQs a mostrar. Si lo dejas vacío, se mostrarán todas.',
			'required' => 0,
			'conditional_logic' => 0,
			'post_type' => array(
				0 => 'faq',
			),
			'filters' => array(
				0 => 'search',
			),
			'return_format' => 'object',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'front_page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_proyecto_testimonio',
	'title' => 'Testimonio Asociado',
	'fields' => array(
		array(
			'key' => 'field_testimonio_asociado',
			'label' => 'Testimonio del Cliente',
			'name' => 'testimonio_asociado',
			'type' => 'post_object',
			'instructions' => 'Selecciona un testimonio para mostrar en la página individual de este proyecto.',
			'required' => 0,
			'post_type' => array(
				0 => 'testimonio',
			),
			'return_format' => 'object',
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'proyecto',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
));

acf_add_local_field_group(array(
	'ID' => '',
	'ID' => '',
	'key' => 'group_proyecto_detalles',
	'title' => 'Detalles del Proyecto',
	'fields' => array(
		array(
			'key' => 'field_client_name',
			'label' => 'Nombre del Cliente',
			'name' => 'client_name',
			'type' => 'text',
			'instructions' => 'Nombre del cliente o empresa para este proyecto.',
		),
		array(
			'key' => 'field_live_url',
			'label' => 'URL en Vivo',
			'name' => 'live_url',
			'type' => 'url',
			'instructions' => 'Enlace al proyecto publicado (opcional).',
		),
		array(
			'key' => 'field_css_gradient',
			'label' => 'Gradiente CSS (Opcional)',
			'name' => 'css_gradient',
			'type' => 'text',
			'instructions' => 'Ej: linear-gradient(135deg, #0a1f28 0%, #144257 50%, #287799 100%)',
		),
		array(
			'key' => 'field_website_status',
			'label' => 'Estado del Sitio Web',
			'name' => '_website_status',
			'type' => 'radio',
			'instructions' => 'Indica si el sitio está online o ha sido dado de baja.',
			'choices' => array(
				'online' => 'Online',
				'offline' => 'Offline (Mostrar nota aclaratoria)',
			),
			'default_value' => 'online',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'proyecto',
			),
		),
	),
	'position' => 'normal',
	'style' => 'default',
));

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_testimonio_meta',
	'title' => 'Datos del Testimonio',
	'fields' => array(
		array(
			'key' => 'field_testimonial_content',
			'label' => 'Reseña',
			'name' => 'testimonial_content',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_testimonial_country',
			'label' => 'País',
			'name' => 'testimonial_country',
			'type' => 'text',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'testimonio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
));

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_sobre_mi_page',
	'title' => 'Ajustes de Sobre Mí',
	'fields' => array(
		array(
			'key' => 'tab_sobre_mi_hero',
			'label' => 'Hero',
			'type' => 'tab',
		),
		array(
			'key' => 'field_sobre_mi_hero_kicker',
			'label' => 'Kicker',
			'name' => 'sobre_mi_hero_kicker',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_hero_headline_prefix',
			'label' => 'Titular (Prefijo)',
			'name' => 'sobre_mi_hero_headline_prefix',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_hero_headline_highlight',
			'label' => 'Titular (Destacado)',
			'name' => 'sobre_mi_hero_headline_highlight',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_hero_description',
			'label' => 'Descripción',
			'name' => 'sobre_mi_hero_description',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_sobre_mi_metric_1_number',
			'label' => 'Métrica 1 (Número)',
			'name' => 'sobre_mi_metric_1_number',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_metric_1_label',
			'label' => 'Métrica 1 (Etiqueta)',
			'name' => 'sobre_mi_metric_1_label',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_metric_2_number',
			'label' => 'Métrica 2 (Número)',
			'name' => 'sobre_mi_metric_2_number',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_metric_2_label',
			'label' => 'Métrica 2 (Etiqueta)',
			'name' => 'sobre_mi_metric_2_label',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_metric_3_number',
			'label' => 'Métrica 3 (Número)',
			'name' => 'sobre_mi_metric_3_number',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_metric_3_label',
			'label' => 'Métrica 3 (Etiqueta)',
			'name' => 'sobre_mi_metric_3_label',
			'type' => 'text',
		),
		array(
			'key' => 'tab_sobre_mi_bio',
			'label' => 'Biografía',
			'type' => 'tab',
		),
		array(
			'key' => 'field_sobre_mi_bio_headline_prefix',
			'label' => 'Titular (Prefijo)',
			'name' => 'sobre_mi_bio_headline_prefix',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_bio_headline_highlight',
			'label' => 'Titular (Destacado)',
			'name' => 'sobre_mi_bio_headline_highlight',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_bio_text_1',
			'label' => 'Texto Principal',
			'name' => 'sobre_mi_bio_text_1',
			'type' => 'wysiwyg',
			'media_upload' => 0,
		),
		array(
			'key' => 'field_sobre_mi_bio_quote',
			'label' => 'Frase Destacada (Quote)',
			'name' => 'sobre_mi_bio_quote',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_sobre_mi_bio_text_2',
			'label' => 'Texto Secundario',
			'name' => 'sobre_mi_bio_text_2',
			'type' => 'wysiwyg',
			'media_upload' => 0,
		),
		array(
			'key' => 'field_sobre_mi_stack_title',
			'label' => 'Título Stack Tecnológico',
			'name' => 'sobre_mi_stack_title',
			'type' => 'text',
			'default_value' => 'Ecosistema & Stack Core',
		),
		array(
			'key' => 'tab_sobre_mi_trayectoria',
			'label' => 'Trayectoria',
			'type' => 'tab',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_headline',
			'label' => 'Titular',
			'name' => 'sobre_mi_trayectoria_headline',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_1_period',
			'label' => 'Trayectoria 1 (Período)',
			'name' => 'sobre_mi_trayectoria_1_period',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_1_role',
			'label' => 'Trayectoria 1 (Rol)',
			'name' => 'sobre_mi_trayectoria_1_role',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_1_description',
			'label' => 'Trayectoria 1 (Descripción)',
			'name' => 'sobre_mi_trayectoria_1_description',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_2_period',
			'label' => 'Trayectoria 2 (Período)',
			'name' => 'sobre_mi_trayectoria_2_period',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_2_role',
			'label' => 'Trayectoria 2 (Rol)',
			'name' => 'sobre_mi_trayectoria_2_role',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_2_description',
			'label' => 'Trayectoria 2 (Descripción)',
			'name' => 'sobre_mi_trayectoria_2_description',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_3_period',
			'label' => 'Trayectoria 3 (Período)',
			'name' => 'sobre_mi_trayectoria_3_period',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_3_role',
			'label' => 'Trayectoria 3 (Rol)',
			'name' => 'sobre_mi_trayectoria_3_role',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_3_description',
			'label' => 'Trayectoria 3 (Descripción)',
			'name' => 'sobre_mi_trayectoria_3_description',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_4_period',
			'label' => 'Trayectoria 4 (Período)',
			'name' => 'sobre_mi_trayectoria_4_period',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_4_role',
			'label' => 'Trayectoria 4 (Rol)',
			'name' => 'sobre_mi_trayectoria_4_role',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_4_description',
			'label' => 'Trayectoria 4 (Descripción)',
			'name' => 'sobre_mi_trayectoria_4_description',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_5_period',
			'label' => 'Trayectoria 5 (Período)',
			'name' => 'sobre_mi_trayectoria_5_period',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_5_role',
			'label' => 'Trayectoria 5 (Rol)',
			'name' => 'sobre_mi_trayectoria_5_role',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_trayectoria_5_description',
			'label' => 'Trayectoria 5 (Descripción)',
			'name' => 'sobre_mi_trayectoria_5_description',
			'type' => 'textarea',
		),
		array(
			'key' => 'tab_sobre_mi_valores',
			'label' => 'Valores',
			'type' => 'tab',
		),
		array(
			'key' => 'field_sobre_mi_valores_headline',
			'label' => 'Titular',
			'name' => 'sobre_mi_valores_headline',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_valores_text',
			'label' => 'Texto de Valores',
			'name' => 'sobre_mi_valores_text',
			'type' => 'wysiwyg',
			'media_upload' => 0,
		),
		array(
			'key' => 'tab_sobre_mi_cta',
			'label' => 'Llamado a la Acción (CTA)',
			'type' => 'tab',
		),
		array(
			'key' => 'field_sobre_mi_cta_kicker',
			'label' => 'Kicker',
			'name' => 'sobre_mi_cta_kicker',
			'type' => 'text',
			'default_value' => 'Contacto',
		),
		array(
			'key' => 'field_sobre_mi_cta_headline',
			'label' => 'Titular',
			'name' => 'sobre_mi_cta_headline',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_cta_subheadline',
			'label' => 'Subtítulo',
			'name' => 'sobre_mi_cta_subheadline',
			'type' => 'textarea',
		),
		array(
			'key' => 'field_sobre_mi_cta_btn_label',
			'label' => 'Etiqueta del Botón',
			'name' => 'sobre_mi_cta_btn_label',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_cta_btn_url',
			'label' => 'URL del Botón',
			'name' => 'sobre_mi_cta_btn_url',
			'type' => 'text',
		),
		array(
			'key' => 'field_sobre_mi_cta_guarantee',
			'label' => 'Garantía / Nota bajo el botón',
			'name' => 'sobre_mi_cta_guarantee',
			'type' => 'text',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-sobre-mi.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
));

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_global_hero_cta',
	'title' => 'Configuración de Página (Héroe y CTA)',
	'fields' => array(
		array('key' => 'field_hero_kicker', 'label' => 'Kicker (Subtítulo superior)', 'name' => 'hero_kicker', 'type' => 'text'),
		array('key' => 'field_hero_h1_normal', 'label' => 'H1 Texto Normal', 'name' => 'hero_h1_normal', 'type' => 'text'),
		array('key' => 'field_hero_h1_highlight', 'label' => 'H1 Texto Resaltado', 'name' => 'hero_h1_highlight', 'type' => 'text'),
		array('key' => 'field_hero_description', 'label' => 'Descripción del Héroe', 'name' => 'hero_description', 'type' => 'textarea', 'rows' => 3),
		array('key' => 'field_cta_kicker', 'label' => 'CTA Kicker', 'name' => 'cta_kicker', 'type' => 'text'),
		array('key' => 'field_cta_h2', 'label' => 'CTA Título', 'name' => 'cta_h2', 'type' => 'text'),
		array('key' => 'field_cta_description', 'label' => 'CTA Descripción', 'name' => 'cta_description', 'type' => 'textarea', 'rows' => 3),
		array('key' => 'field_cta_button_text', 'label' => 'CTA Botón Texto', 'name' => 'cta_button_text', 'type' => 'text'),
		array('key' => 'field_cta_button_url', 'label' => 'CTA Botón URL', 'name' => 'cta_button_url', 'type' => 'text'),
	),
	'location' => array(
		array(array('param' => 'page_template', 'operator' => '==', 'value' => 'page-servicios.php')),
		array(array('param' => 'page_template', 'operator' => '==', 'value' => 'page-portafolio.php')),
		array(array('param' => 'page_template', 'operator' => '==', 'value' => 'page-blog.php')),
		array(array('param' => 'page_template', 'operator' => '==', 'value' => 'page-contacto.php')),
		array(array('param' => 'page_type', 'operator' => '==', 'value' => 'posts_page')),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
));

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_servicios_contenido',
	'title' => 'Contenido Servicios',
	'fields' => array(
		array('key' => 'field_servicios_para_ti_titulo', 'label' => 'Título "Esto es para ti"', 'name' => 'servicios_para_ti_titulo', 'type' => 'text', 'default_value' => 'Esto es para ti si...'),
		array('key' => 'field_servicios_para_ti', 'label' => 'Esto es para ti (Una por línea)', 'name' => 'servicios_para_ti', 'type' => 'textarea', 'rows' => 5),
		array('key' => 'field_servicios_no_para_ti_titulo', 'label' => 'Título "NO es para ti"', 'name' => 'servicios_no_para_ti_titulo', 'type' => 'text', 'default_value' => 'Y esto NO es para ti si...'),
		array('key' => 'field_servicios_no_para_ti', 'label' => 'Esto NO es para ti (Una por línea)', 'name' => 'servicios_no_para_ti', 'type' => 'textarea', 'rows' => 5),
		array('key' => 'field_servicios_proceso_kicker', 'label' => 'Proceso Kicker', 'name' => 'servicios_proceso_kicker', 'type' => 'text', 'default_value' => 'Metodología'),
		array('key' => 'field_servicios_proceso_titulo', 'label' => 'Proceso Título', 'name' => 'servicios_proceso_titulo', 'type' => 'text', 'default_value' => 'Cómo Trabajo'),
		array('key' => 'field_servicios_proceso_desc', 'label' => 'Proceso Descripción', 'name' => 'servicios_proceso_desc', 'type' => 'textarea', 'rows' => 2, 'default_value' => 'Un proceso claro y transparente de principio a fin, diseñado para agencias y proyectos serios.'),
		array('key' => 'field_servicios_proceso_1_titulo', 'label' => 'Proceso Paso 1 Título', 'name' => 'servicios_proceso_1_titulo', 'type' => 'text', 'default_value' => 'Diagnóstico'),
		array('key' => 'field_servicios_proceso_1_desc', 'label' => 'Proceso Paso 1 Descripción', 'name' => 'servicios_proceso_1_desc', 'type' => 'textarea', 'rows' => 2, 'default_value' => 'Analizo tu situación actual, objetivos y restricciones técnicas para definir la estrategia de desarrollo correcta.'),
		array('key' => 'field_servicios_proceso_2_titulo', 'label' => 'Proceso Paso 2 Título', 'name' => 'servicios_proceso_2_titulo', 'type' => 'text', 'default_value' => 'Propuesta'),
		array('key' => 'field_servicios_proceso_2_desc', 'label' => 'Proceso Paso 2 Descripción', 'name' => 'servicios_proceso_2_desc', 'type' => 'textarea', 'rows' => 2, 'default_value' => 'Presento un plan técnico detallado con alcance, tiempos y costes exactos. Transparencia total, sin sorpresas ocultas.'),
		array('key' => 'field_servicios_proceso_3_titulo', 'label' => 'Proceso Paso 3 Título', 'name' => 'servicios_proceso_3_titulo', 'type' => 'text', 'default_value' => 'Desarrollo'),
		array('key' => 'field_servicios_proceso_3_desc', 'label' => 'Proceso Paso 3 Descripción', 'name' => 'servicios_proceso_3_desc', 'type' => 'textarea', 'rows' => 2, 'default_value' => 'Ejecuto el trabajo utilizando herramientas de IA de última generación, entregando avances verificables en cada sprint.'),
		array('key' => 'field_servicios_proceso_4_titulo', 'label' => 'Proceso Paso 4 Título', 'name' => 'servicios_proceso_4_titulo', 'type' => 'text', 'default_value' => 'Entrega y Soporte'),
		array('key' => 'field_servicios_proceso_4_desc', 'label' => 'Proceso Paso 4 Descripción', 'name' => 'servicios_proceso_4_desc', 'type' => 'textarea', 'rows' => 2, 'default_value' => 'Despliegue controlado en producción (Zero Downtime) con documentación completa y soporte técnico post-lanzamiento.'),
	),
	'location' => array(
		array(array('param' => 'page_template', 'operator' => '==', 'value' => 'page-servicios.php')),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
));

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_contacto_page',
	'title' => 'Ajustes de Página de Contacto',
	'fields' => array(
		// Tab Formulario
		array(
			'key' => 'tab_contacto_form',
			'label' => 'Formulario',
			'type' => 'tab',
		),
		array(
			'key' => 'field_contacto_form_title',
			'label' => 'Título del Formulario',
			'name' => 'contacto_form_title',
			'type' => 'text',
			'default_value' => 'Formulario de contacto',
		),
		array(
			'key' => 'field_contacto_form_success_title',
			'label' => 'Aviso Éxito (Título)',
			'name' => 'contacto_form_success_title',
			'type' => 'text',
			'default_value' => '¡Mensaje enviado con éxito!',
		),
		array(
			'key' => 'field_contacto_form_success_desc',
			'label' => 'Aviso Éxito (Descripción)',
			'name' => 'contacto_form_success_desc',
			'type' => 'textarea',
			'rows' => 2,
			'default_value' => 'Gracias por contactarme. He recibido tu mensaje y me pondré en contacto contigo en menos de 24 horas.',
		),
		array(
			'key' => 'field_contacto_form_error_text',
			'label' => 'Aviso Error',
			'name' => 'contacto_form_error_text',
			'type' => 'textarea',
			'rows' => 2,
			'default_value' => 'Hubo un error al enviar tu mensaje. Por favor, verifica los campos e inténtalo de nuevo.',
		),
		array(
			'key' => 'field_contacto_field_name_label',
			'label' => 'Campo Nombre (Etiqueta)',
			'name' => 'contacto_field_name_label',
			'type' => 'text',
			'default_value' => 'Nombre completo *',
		),
		array(
			'key' => 'field_contacto_field_name_placeholder',
			'label' => 'Campo Nombre (Placeholder)',
			'name' => 'contacto_field_name_placeholder',
			'type' => 'text',
			'default_value' => 'Tu nombre o agencia',
		),
		array(
			'key' => 'field_contacto_field_email_label',
			'label' => 'Campo Email (Etiqueta)',
			'name' => 'contacto_field_email_label',
			'type' => 'text',
			'default_value' => 'Email profesional *',
		),
		array(
			'key' => 'field_contacto_field_email_placeholder',
			'label' => 'Campo Email (Placeholder)',
			'name' => 'contacto_field_email_placeholder',
			'type' => 'text',
			'default_value' => 'tu@email.com',
		),
		array(
			'key' => 'field_contacto_field_company_label',
			'label' => 'Campo Empresa (Etiqueta)',
			'name' => 'contacto_field_company_label',
			'type' => 'text',
			'default_value' => 'Empresa (Opcional)',
		),
		array(
			'key' => 'field_contacto_field_company_placeholder',
			'label' => 'Campo Empresa (Placeholder)',
			'name' => 'contacto_field_company_placeholder',
			'type' => 'text',
			'default_value' => 'Nombre de tu empresa',
		),
		array(
			'key' => 'field_contacto_field_service_label',
			'label' => 'Campo Servicio (Etiqueta)',
			'name' => 'contacto_field_service_label',
			'type' => 'text',
			'default_value' => 'Servicio de interés',
		),
		array(
			'key' => 'field_contacto_field_service_options',
			'label' => 'Opciones de Servicio (Una por línea)',
			'name' => 'contacto_field_service_options',
			'type' => 'textarea',
			'rows' => 6,
			'default_value' => "Desarrollo Web a Medida\nMantenimiento Web\nIntegración de Agentes IA\nOptimización SEO/GEO\nMigración / Zero Downtime\nOtro requerimiento",
		),
		array(
			'key' => 'field_contacto_field_budget_label',
			'label' => 'Campo Presupuesto (Etiqueta)',
			'name' => 'contacto_field_budget_label',
			'type' => 'text',
			'default_value' => 'Presupuesto Estimado',
		),
		array(
			'key' => 'field_contacto_field_budget_options',
			'label' => 'Opciones de Presupuesto (Una por línea)',
			'name' => 'contacto_field_budget_options',
			'type' => 'textarea',
			'rows' => 5,
			'default_value' => "No estoy seguro / Quiero consultarlo\nMenos de 1.000€\n1.000€ - 3.000€\n3.000€ - 10.000€\nMás de 10.000€",
		),
		array(
			'key' => 'field_contacto_field_message_label',
			'label' => 'Campo Mensaje (Etiqueta)',
			'name' => 'contacto_field_message_label',
			'type' => 'text',
			'default_value' => 'Cuéntame sobre tu proyecto *',
		),
		array(
			'key' => 'field_contacto_field_message_placeholder',
			'label' => 'Campo Mensaje (Placeholder)',
			'name' => 'contacto_field_message_placeholder',
			'type' => 'text',
			'default_value' => 'Describe brevemente tus objetivos, plazos y cualquier restricción técnica...',
		),
		array(
			'key' => 'field_contacto_form_btn_label',
			'label' => 'Botón de Envío (Texto)',
			'name' => 'contacto_form_btn_label',
			'type' => 'text',
			'default_value' => 'Enviar Mensaje',
		),

		// Tab Información Directa & Testimonio
		array(
			'key' => 'tab_contacto_direct',
			'label' => 'Contacto Directo & Testimonio',
			'type' => 'tab',
		),
		array(
			'key' => 'field_contacto_direct_title',
			'label' => 'Título Contacto Directo',
			'name' => 'contacto_direct_title',
			'type' => 'text',
			'default_value' => 'Contacto Directo',
		),
		array(
			'key' => 'field_contacto_email_label',
			'label' => 'Etiqueta Email',
			'name' => 'contacto_email_label',
			'type' => 'text',
			'default_value' => 'Email Profesional',
		),
		array(
			'key' => 'field_contacto_whatsapp_sublabel',
			'label' => 'Subetiqueta WhatsApp',
			'name' => 'contacto_whatsapp_sublabel',
			'type' => 'text',
			'default_value' => 'Chat Directo',
		),
		array(
			'key' => 'field_contacto_social_title',
			'label' => 'Título Redes Sociales',
			'name' => 'contacto_social_title',
			'type' => 'text',
			'default_value' => 'Redes Sociales',
		),
		array(
			'key' => 'field_contacto_testimonial_quote',
			'label' => 'Testimonio (Cita)',
			'name' => 'contacto_testimonial_quote',
			'type' => 'textarea',
			'rows' => 3,
			'default_value' => 'Un gran profesional, seguimos trabajando con él ya que estamos muy contentos con su desempeño.',
		),
		array(
			'key' => 'field_contacto_testimonial_author',
			'label' => 'Testimonio (Autor)',
			'name' => 'contacto_testimonial_author',
			'type' => 'text',
			'default_value' => 'Khadim Cissé',
		),

		// Tab Preguntas Frecuentes
		array(
			'key' => 'tab_contacto_faq',
			'label' => 'Preguntas Frecuentes',
			'type' => 'tab',
		),
		array(
			'key' => 'field_contacto_faq_kicker',
			'label' => 'FAQ Kicker',
			'name' => 'contacto_faq_kicker',
			'type' => 'text',
			'default_value' => 'Preguntas Frecuentes',
		),
		array(
			'key' => 'field_contacto_faq_titulo',
			'label' => 'FAQ Título',
			'name' => 'contacto_faq_titulo',
			'type' => 'text',
			'default_value' => 'Preguntas habituales antes de empezar',
		),
		array(
			'key' => 'field_contacto_faq_desc',
			'label' => 'FAQ Descripción',
			'name' => 'contacto_faq_desc',
			'type' => 'textarea',
			'rows' => 2,
			'default_value' => 'Despeja tus dudas sobre tiempos, flujo de trabajo, comunicación y costes antes de enviar el formulario.',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-contacto.php',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
));

acf_add_local_field_group(array(
	'ID' => '',
	'ID' => '',
	'key' => 'group_blog_settings',
	'title' => 'Ajustes de Blog',
	'fields' => array(
		array(
			'key' => 'field_blog_filter_all_label',
			'label' => 'Etiqueta Filtro "Todos"',
			'name' => 'blog_filter_all_label',
			'type' => 'text',
			'default_value' => 'Todos los Artículos',
		),
		array(
			'key' => 'field_blog_load_more_label',
			'label' => 'Etiqueta Botón "Cargar Más"',
			'name' => 'blog_load_more_label',
			'type' => 'text',
			'default_value' => 'Cargar más artículos',
		),
		array(
			'key' => 'field_blog_loading_label',
			'label' => 'Etiqueta Estado "Cargando"',
			'name' => 'blog_loading_label',
			'type' => 'text',
			'default_value' => 'Cargando...',
		),
		array(
			'key' => 'field_blog_empty_title',
			'label' => 'Título Estado Vacío',
			'name' => 'blog_empty_title',
			'type' => 'text',
			'default_value' => 'No se encontraron artículos',
		),
		array(
			'key' => 'field_blog_empty_desc',
			'label' => 'Descripción Estado Vacío',
			'name' => 'blog_empty_desc',
			'type' => 'textarea',
			'rows' => 2,
			'default_value' => 'Aún no hay contenido publicado en el blog.',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-blog.php',
			),
		),
		array(
			array(
				'param' => 'page_type',
				'operator' => '==',
				'value' => 'posts_page',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
));

acf_add_local_field_group(array (
  'ID' => '',
  'ID' => '',
  'key' => 'group_home_page',
  'title' => 'Ajustes de Inicio (Home)',
  'fields' => 
  array (
    0 => 
    array (
      'key' => 'field_tab_hero',
      'label' => 'Hero',
      'name' => '',
      'aria-label' => '',
      'type' => 'tab',
      'value' => false,
      'menu_order' => 0,
      'instructions' => '',
      'required' => 0,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
      'selected' => 0,
    ),
    1 => 
    array (
      'key' => 'field_hero_headline',
      'label' => 'Titular (Headline)',
      'name' => 'hero_headline',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 1,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    2 => 
    array (
      'key' => 'field_hero_subheadline',
      'label' => 'Subtítulo (Subheadline)',
      'name' => 'hero_subheadline',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 2,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    3 => 
    array (
      'key' => 'field_hero_cta_label',
      'label' => 'Texto del Botón',
      'name' => 'hero_cta_label',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 3,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    4 => 
    array (
      'key' => 'field_hero_cta_url',
      'label' => 'URL del Botón',
      'name' => 'hero_cta_url',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 4,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    44 => array (
      'key' => 'field_hero_cta_2_label',
      'label' => 'Texto del Botón Secundario',
      'name' => 'hero_cta_2_label',
      'type' => 'text',
    ),
    53 => array (
      'key' => 'field_hero_cta_2_url',
      'label' => 'URL del Botón Secundario',
      'name' => 'hero_cta_2_url',
      'type' => 'text',
    ),
    5 => 
    array (
      'key' => 'field_home_hero_kicker',
      'label' => 'Kicker (Texto sobre el título)',
      'name' => 'hero_kicker',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 5,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    6 => 
    array (
      'key' => 'field_home_hero_image',
      'label' => 'Imagen del Hero',
      'name' => 'hero_image',
      'aria-label' => '',
      'type' => 'image',
      'value' => NULL,
      'menu_order' => 6,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'return_format' => 'array',
      'preview_size' => 'medium',
      'library' => 'all',
      'min_width' => 0,
      'min_height' => 0,
      'min_size' => 0,
      'max_width' => 0,
      'max_height' => 0,
      'max_size' => 0,
      'mime_types' => '',
    ),
    7 => 
    array (
      'key' => 'field_tab_metrics',
      'label' => 'Métricas',
      'name' => '',
      'aria-label' => '',
      'type' => 'tab',
      'value' => false,
      'menu_order' => 7,
      'instructions' => '',
      'required' => 0,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
      'selected' => 0,
    ),
    8 => 
    array (
      'key' => 'field_metric_1_val',
      'label' => 'Métrica 1 - Valor',
      'name' => 'metric_1_val',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 8,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    9 => 
    array (
      'key' => 'field_metric_1_lab',
      'label' => 'Métrica 1 - Etiqueta',
      'name' => 'metric_1_lab',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 9,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    10 => 
    array (
      'key' => 'field_metric_2_val',
      'label' => 'Métrica 2 - Valor',
      'name' => 'metric_2_val',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 10,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    11 => 
    array (
      'key' => 'field_metric_2_lab',
      'label' => 'Métrica 2 - Etiqueta',
      'name' => 'metric_2_lab',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 11,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    12 => 
    array (
      'key' => 'field_metric_3_val',
      'label' => 'Métrica 3 - Valor',
      'name' => 'metric_3_val',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 12,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    13 => 
    array (
      'key' => 'field_metric_3_lab',
      'label' => 'Métrica 3 - Etiqueta',
      'name' => 'metric_3_lab',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 13,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    14 => 
    array (
      'key' => 'field_tab_about',
      'label' => 'Sobre Mí',
      'name' => '',
      'aria-label' => '',
      'type' => 'tab',
      'value' => false,
      'menu_order' => 14,
      'instructions' => '',
      'required' => 0,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
      'selected' => 0,
    ),
    45 => array (
      'key' => 'field_about_kicker',
      'label' => 'Kicker Sobre Mí',
      'name' => 'about_kicker',
      'type' => 'text',
    ),
    15 => 
    array (
      'key' => 'field_about_headline',
      'label' => 'Titular',
      'name' => 'about_headline',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 15,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    16 => 
    array (
      'key' => 'field_about_bio',
      'label' => 'Biografía',
      'name' => 'about_bio',
      'aria-label' => '',
      'type' => 'wysiwyg',
      'value' => NULL,
      'menu_order' => 16,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'tabs' => 'all',
      'toolbar' => 'full',
      'media_upload' => 1,
      'default_value' => '',
      'delay' => 0,
    ),
    17 => 
    array (
      'key' => 'field_tab_methodology',
      'label' => 'Metodología',
      'name' => '',
      'aria-label' => '',
      'type' => 'tab',
      'value' => false,
      'menu_order' => 17,
      'instructions' => '',
      'required' => 0,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
      'selected' => 0,
    ),
    18 => 
    array (
      'key' => 'field_method_kicker',
      'label' => 'Kicker (Ej: Metodología)',
      'name' => 'method_kicker',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 18,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    19 => 
    array (
      'key' => 'field_method_title',
      'label' => 'Título Principal',
      'name' => 'method_title',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 19,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    20 => 
    array (
      'key' => 'field_method_desc',
      'label' => 'Descripción General',
      'name' => 'method_desc',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 20,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    21 => 
    array (
      'key' => 'field_step_1_letter',
      'label' => 'Paso 1 - Letra',
      'name' => 'step_1_letter',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 21,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    22 => 
    array (
      'key' => 'field_step_1_title',
      'label' => 'Paso 1 - Título',
      'name' => 'step_1_title',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 22,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    23 => 
    array (
      'key' => 'field_step_1_desc',
      'label' => 'Paso 1 - Descripción',
      'name' => 'step_1_desc',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 23,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    24 => 
    array (
      'key' => 'field_step_2_letter',
      'label' => 'Paso 2 - Letra',
      'name' => 'step_2_letter',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 24,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    25 => 
    array (
      'key' => 'field_step_2_title',
      'label' => 'Paso 2 - Título',
      'name' => 'step_2_title',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 25,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    26 => 
    array (
      'key' => 'field_step_2_desc',
      'label' => 'Paso 2 - Descripción',
      'name' => 'step_2_desc',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 26,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    27 => 
    array (
      'key' => 'field_step_3_letter',
      'label' => 'Paso 3 - Letra',
      'name' => 'step_3_letter',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 27,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    28 => 
    array (
      'key' => 'field_step_3_title',
      'label' => 'Paso 3 - Título',
      'name' => 'step_3_title',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 28,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    29 => 
    array (
      'key' => 'field_step_3_desc',
      'label' => 'Paso 3 - Descripción',
      'name' => 'step_3_desc',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 29,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    30 => 
    array (
      'key' => 'field_step_4_letter',
      'label' => 'Paso 4 - Letra',
      'name' => 'step_4_letter',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 30,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    31 => 
    array (
      'key' => 'field_step_4_title',
      'label' => 'Paso 4 - Título',
      'name' => 'step_4_title',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 31,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    32 => 
    array (
      'key' => 'field_step_4_desc',
      'label' => 'Paso 4 - Descripción',
      'name' => 'step_4_desc',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 32,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    33 => 
    array (
      'key' => 'field_step_5_letter',
      'label' => 'Paso 5 - Letra',
      'name' => 'step_5_letter',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 33,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    34 => 
    array (
      'key' => 'field_step_5_title',
      'label' => 'Paso 5 - Título',
      'name' => 'step_5_title',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 34,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    35 => 
    array (
      'key' => 'field_step_5_desc',
      'label' => 'Paso 5 - Descripción',
      'name' => 'step_5_desc',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 35,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    46 => array('key' => 'field_tab_home_portfolio', 'label' => 'Portafolio', 'type' => 'tab'),
    47 => array('key' => 'field_home_portfolio_kicker', 'label' => 'Kicker Portafolio', 'name' => 'home_portfolio_kicker', 'type' => 'text'),
    48 => array('key' => 'field_home_portfolio_title', 'label' => 'Título Portafolio', 'name' => 'home_portfolio_title', 'type' => 'text'),
    49 => array('key' => 'field_home_portfolio_desc', 'label' => 'Descripción Portafolio', 'name' => 'home_portfolio_desc', 'type' => 'textarea', 'rows' => 3),
    50 => array('key' => 'field_tab_home_services', 'label' => 'Servicios', 'type' => 'tab'),
    51 => array('key' => 'field_home_services_kicker', 'label' => 'Kicker Servicios', 'name' => 'home_services_kicker', 'type' => 'text', 'default_value' => 'Servicios'),
    52 => array('key' => 'field_home_services_title', 'label' => 'Título Servicios', 'name' => 'home_services_title', 'type' => 'text', 'default_value' => 'Mis Soluciones'),
    53 => array('key' => 'field_tab_home_testimonials', 'label' => 'Opiniones / Testimonios', 'type' => 'tab'),
    54 => array('key' => 'field_home_testimonials_kicker', 'label' => 'Kicker Opiniones', 'name' => 'home_testimonials_kicker', 'type' => 'text', 'default_value' => 'Opiniones'),
    55 => array('key' => 'field_home_testimonials_title', 'label' => 'Título Opiniones', 'name' => 'home_testimonials_title', 'type' => 'text', 'default_value' => 'Lo que dicen mis clientes'),
    56 => array('key' => 'field_tab_home_faq', 'label' => 'Preguntas Frecuentes', 'type' => 'tab'),
    57 => array('key' => 'field_home_faq_kicker', 'label' => 'Kicker FAQ', 'name' => 'home_faq_kicker', 'type' => 'text', 'default_value' => 'Preguntas frecuentes'),
    58 => array('key' => 'field_home_faq_title', 'label' => 'Título FAQ', 'name' => 'home_faq_title', 'type' => 'text', 'default_value' => 'Resolvamos tus dudas'),
    59 => array('key' => 'field_home_faq_desc', 'label' => 'Descripción FAQ', 'name' => 'home_faq_desc', 'type' => 'textarea', 'rows' => 3, 'default_value' => 'Las preguntas más comunes que recibo de agencias y empresas antes de trabajar juntos.'),
    60 => array('key' => 'field_tab_home_blog', 'label' => 'Blog', 'type' => 'tab'),
    61 => array('key' => 'field_home_blog_kicker', 'label' => 'Kicker Blog', 'name' => 'home_blog_kicker', 'type' => 'text', 'default_value' => 'Blog'),
    62 => array('key' => 'field_home_blog_title', 'label' => 'Título Blog', 'name' => 'home_blog_title', 'type' => 'text', 'default_value' => 'Últimos artículos'),
    63 => array('key' => 'field_home_cta_tab', 'label' => 'Llamado a la Acción (CTA)', 'type' => 'tab'),
    64 => array('key' => 'field_home_cta_headline', 'label' => 'Título del CTA', 'name' => 'cta_headline', 'type' => 'text', 'default_value' => '¿Tienes un proyecto en mente?'),
    65 => array('key' => 'field_home_cta_subheadline', 'label' => 'Subtítulo del CTA', 'name' => 'cta_subheadline', 'type' => 'textarea', 'rows' => 3, 'default_value' => 'Cuéntame qué necesitas y te digo cómo puedo ayudarte. Sin compromiso.'),
    66 => array('key' => 'field_home_cta_btn_label', 'label' => 'Texto del Botón CTA', 'name' => 'cta_btn_label', 'type' => 'text', 'default_value' => 'Hablemos'),
    67 => array('key' => 'field_home_cta_btn_url', 'label' => 'URL del Botón CTA', 'name' => 'cta_btn_url', 'type' => 'text', 'default_value' => '#contacto'),
    68 => array('key' => 'field_home_cta_subtext', 'label' => 'Garantía / Texto inferior', 'name' => 'cta_subtext', 'type' => 'text', 'default_value' => 'Respuesta en menos de 24 horas'),
  ),
  'location' => 
  array (
    0 => 
    array (
      0 => 
      array (
        'param' => 'page_type',
        'operator' => '==',
        'value' => 'front_page',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => 
  array (
    0 => 'the_content',
  ),
  'active' => true,
  'description' => '',
  'show_in_rest' => false,
  'display_title' => '',
  'allow_ai_access' => false,
  'ai_description' => '',
  '_valid' => true,
));

acf_add_local_field_group(array (
  'ID' => '',
  'ID' => '',
  'key' => 'group_service_details',
  'title' => 'Detalles del Servicio',
  'fields' => 
  array (
    0 => 
    array (
      'key' => 'field_service_icon',
      'label' => 'Nombre del Icono (Ej: code)',
      'name' => 'icon',
      'aria-label' => '',
      'type' => 'text',
      'value' => NULL,
      'menu_order' => 0,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'maxlength' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
    ),
    1 => 
    array (
      'key' => 'field_service_desc',
      'label' => 'Descripción Corta',
      'name' => 'desc',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 1,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
    2 => 
    array (
      'key' => 'field_service_features',
      'label' => 'Características (Una por línea)',
      'name' => 'features',
      'aria-label' => '',
      'type' => 'textarea',
      'value' => NULL,
      'menu_order' => 2,
      'instructions' => '',
      'required' => false,
      'id' => '',
      'class' => '',
      'conditional_logic' => false,
      'wrapper' => 
      array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'new_lines' => '',
      'maxlength' => '',
      'placeholder' => '',
      'rows' => '',
    ),
  ),
  'location' => 
  array (
    0 => 
    array (
      0 => 
      array (
        'param' => 'post_type',
        'operator' => '==',
        'value' => 'servicio',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => 
  array (
  ),
  'active' => true,
  'description' => '',
  'show_in_rest' => false,
  'display_title' => '',
  'allow_ai_access' => false,
  'ai_description' => '',
  '_valid' => true,
));

acf_add_local_field_group(array(
	'ID' => '',
  'ID' => '',
  'key' => 'group_portfolio_settings',
	'title' => 'Ajustes de Portafolio',
	'fields' => array(
		array(
			'key' => 'field_portfolio_sort_order',
			'label' => 'Orden de los Proyectos',
			'name' => 'portfolio_sort_order',
			'type' => 'select',
			'instructions' => 'Selecciona cómo quieres que se ordenen los proyectos en esta página.',
			'choices' => array(
				'date_asc' => 'Más antiguos primero (Fecha de Creación)',
				'date_desc' => 'Más recientes primero (Fecha de Creación)',
				'modified_asc' => 'Más antiguos primero (Fecha de Modificación)',
				'modified_desc' => 'Más recientes primero (Fecha de Modificación)',
				'title_asc' => 'Alfabético (A-Z)',
			),
			'default_value' => 'date_asc',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_portfolio_filter_all_label',
			'label' => 'Etiqueta Filtro "Todos"',
			'name' => 'portfolio_filter_all_label',
			'type' => 'text',
			'default_value' => 'Todos los Proyectos',
		),
		array(
			'key' => 'field_portfolio_load_more_label',
			'label' => 'Etiqueta Botón "Cargar Más"',
			'name' => 'portfolio_load_more_label',
			'type' => 'text',
			'default_value' => 'Cargar más proyectos',
		),
		array(
			'key' => 'field_portfolio_loading_label',
			'label' => 'Etiqueta Estado "Cargando"',
			'name' => 'portfolio_loading_label',
			'type' => 'text',
			'default_value' => 'Cargando...',
		),
		array(
			'key' => 'field_portfolio_empty_title',
			'label' => 'Título Estado Vacío',
			'name' => 'portfolio_empty_title',
			'type' => 'text',
			'default_value' => 'No se encontraron proyectos',
		),
		array(
			'key' => 'field_portfolio_empty_desc',
			'label' => 'Descripción Estado Vacío',
			'name' => 'portfolio_empty_desc',
			'type' => 'textarea',
			'rows' => 2,
			'default_value' => 'Pronto añadiré más casos de estudio a mi portafolio.',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-portafolio.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
));

endif;
